# Generated by Django 3.2.6 on 2021-11-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archers',
            fields=[
                ('a_id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_unit', models.TextField()),
                ('a_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Archer"."archers',
            },
        ),
        migrations.CreateModel(
            name='Cups',
            fields=[
                ('cup_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cup_name', models.TextField()),
                ('host', models.TextField()),
                ('day', models.DateField()),
            ],
            options={
                'db_table': 'Archer"."cups',
            },
        ),
    ]
