# Generated by Django 3.2.6 on 2021-11-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfilter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('g_id', models.IntegerField(primary_key=True, serialize=False)),
                ('g_name', models.TextField()),
            ],
            options={
                'db_table': 'Archer"."groups',
            },
        ),
    ]
