# Generated by Django 3.2.6 on 2021-11-08 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfilter', '0002_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('target', models.TextField()),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfilter.archers')),
                ('cup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfilter.cups')),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfilter.groups')),
            ],
            options={
                'db_table': 'Archer"."individuals',
            },
        ),
    ]
