# Generated by Django 3.2.6 on 2021-11-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfilter', '0003_individuals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individuals',
            old_name='a_id',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='individuals',
            old_name='cup_id',
            new_name='cup',
        ),
        migrations.RenameField(
            model_name='individuals',
            old_name='g_id',
            new_name='g',
        ),
    ]
