# Generated by Django 3.2.6 on 2021-11-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfilter', '0004_auto_20211108_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual_ranks',
            fields=[
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myfilter.individuals')),
                ('tenx', models.IntegerField()),
                ('x', models.IntegerField()),
                ('total', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'Archer"."individual_ranks',
            },
        ),
        migrations.CreateModel(
            name='Individual_scores',
            fields=[
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myfilter.individuals')),
                ('tenx', models.IntegerField()),
                ('x', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'Archer"."individual_scores',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('t', models.IntegerField(primary_key=True, serialize=False)),
                ('t_name', models.TextField()),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_cup', to='myfilter.cups')),
                ('i1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual1', to='myfilter.individuals')),
                ('i2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual2', to='myfilter.individuals')),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual3', to='myfilter.individuals')),
            ],
            options={
                'db_table': 'Archer"."teams',
            },
        ),
        migrations.CreateModel(
            name='Team_ranks',
            fields=[
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myfilter.teams')),
                ('tenx', models.IntegerField()),
                ('x', models.IntegerField()),
                ('total', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'Archer"."team_ranks',
            },
        ),
        migrations.CreateModel(
            name='Team_scores',
            fields=[
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myfilter.teams')),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('score_3', models.IntegerField()),
                ('tenx', models.IntegerField()),
                ('x', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'Archer"."team_scores',
            },
        ),
    ]
